### ISSUE TITLE
Q: Is there any similar behaving keyboards but like US-international layout?

### ISSUE THREAD

**Issue by kiwi0fruit** [vitSkalicky/klavesnice#8]
The way diacritics is typed in this keyboard is very convenient and widely used on PC - it's called [dead keys](https://en.wikipedia.org/wiki/Dead_keys). It is used in keyboard layouts like [US international](https://en.wikipedia.org/wiki/US_international_keyboard#US-International) (that has different common diacritics than Czech). I was searching for android keyboard with diacritics dead keys like US-international but found none. Your keyboard is the closest I found - it behaves the right way, but has different diacritical marks.

Are you aware of any other android keyboards with dead keys for diacritics (not necessary US-international)?

**Comment by vitSkalicky** [comment]
I didn't find any keyboard with dead keys (that's why I made this app), but I am planning to implement the functionality in some *maintained* FOSS keyboard (such as [simple keyboard](https://github.com/rkkr/simple-keyboard) or [openboard](https://github.com/dslul/openboard) ) **in the future**. I will let you know when (if) I do it.

**Comment by kiwi0fruit** [comment]
Thanks for response.
